
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Javi
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/img/icons8-cd-30.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelImagen = new javax.swing.JLabel();
        jButtonEntrar = new javax.swing.JButton();
        jButtonNoche = new javax.swing.JButton();
        jButtonDia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelImagen.setBackground(new java.awt.Color(0, 204, 51));
        jLabelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inicio.png"))); // NOI18N
        jLabelImagen.setBorder(new javax.swing.border.MatteBorder(null));
        jLabelImagen.setOpaque(true);

        jButtonEntrar.setBackground(new java.awt.Color(0, 255, 153));
        jButtonEntrar.setText("ENTRAR");
        jButtonEntrar.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });

        jButtonNoche.setBackground(new java.awt.Color(0, 255, 153));
        jButtonNoche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-luna-brillante-32 (2).png"))); // NOI18N
        jButtonNoche.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonNoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNocheActionPerformed(evt);
            }
        });

        jButtonDia.setBackground(new java.awt.Color(0, 255, 153));
        jButtonDia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-salida-del-sol-32.png"))); // NOI18N
        jButtonDia.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonDia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNoche, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 67, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNoche, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
        VentanaPrincipal vp = new VentanaPrincipal();
        vp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    private void jButtonDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiaActionPerformed
        modoDiaVerde();
    }//GEN-LAST:event_jButtonDiaActionPerformed

    private void jButtonNocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNocheActionPerformed
        modoNocheVerde();
    }//GEN-LAST:event_jButtonNocheActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDia;
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JButton jButtonNoche;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public void modoDia() {
        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jButtonEntrar.setBackground(new java.awt.Color(51, 204, 255));
        jLabelImagen.setBackground(new java.awt.Color(153, 204, 255));
        jButtonDia.setBackground(new java.awt.Color(51, 204, 255));
        jButtonNoche.setBackground(new java.awt.Color(51, 204, 255));
        jButtonEntrar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDia.setForeground(new java.awt.Color(0, 0, 0));
        jButtonNoche.setForeground(new java.awt.Color(0, 0, 0));
    }

    public void modoNoche() {
        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jLabelImagen.setBackground(new java.awt.Color(0, 102, 102));
        jButtonEntrar.setBackground(new java.awt.Color(0, 102, 102));
        jButtonNoche.setBackground(new java.awt.Color(0, 102, 102));
        jButtonDia.setBackground(new java.awt.Color(0, 102, 102));
        jButtonEntrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDia.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNoche.setForeground(new java.awt.Color(255, 255, 255));
    }
    
    public void modoDiaVerde() {
        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jButtonEntrar.setBackground(new java.awt.Color(0, 255, 153));
        jLabelImagen.setBackground(new java.awt.Color(0, 204, 51));
        jButtonDia.setBackground(new java.awt.Color(0, 255, 153));
        jButtonNoche.setBackground(new java.awt.Color(0, 255, 153));
        jButtonEntrar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDia.setForeground(new java.awt.Color(0, 0, 0));
        jButtonNoche.setForeground(new java.awt.Color(0, 0, 0));
    }

    public void modoNocheVerde() {
        jPanel1.setBackground(new java.awt.Color(0, 51, 0));
        jLabelImagen.setBackground(new java.awt.Color(0, 204, 51));
        jButtonEntrar.setBackground(new java.awt.Color(51, 102, 0));
        jButtonNoche.setBackground(new java.awt.Color(51, 102, 0));
        jButtonDia.setBackground(new java.awt.Color(51, 102, 0));
        jButtonEntrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDia.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNoche.setForeground(new java.awt.Color(255, 255, 255));
    }

}
