
import java.util.ArrayList;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Javi
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    GestorConexion ges = new GestorConexion();

    public VentanaPrincipal() {
        initComponents();
        deshabilitarBotones();
        setIconImage(new ImageIcon(getClass().getResource("/img/icons8-cd-30.png")).getImage());//cambia el icono del jFrame
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaQuerys = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabelManejo = new javax.swing.JLabel();
        jButtonConectar = new javax.swing.JButton();
        jButtonDesconectar = new javax.swing.JButton();
        jButtonModoDia = new javax.swing.JButton();
        jButtonModoNoche = new javax.swing.JButton();
        jLabelINSERTS = new javax.swing.JLabel();
        jButton_Añadir_Equipo = new javax.swing.JButton();
        jTextField_Nombre_Equipo = new javax.swing.JTextField();
        jTextField_Ciudad_Equipo = new javax.swing.JTextField();
        jTextField_Estadio_Equipo = new javax.swing.JTextField();
        jButton_Añadir_Datos = new javax.swing.JButton();
        jTextField_Conferencia = new javax.swing.JTextField();
        jTextField_Division = new javax.swing.JTextField();
        jTextField_Fundacion = new javax.swing.JTextField();
        jTextField_Entrada_NFL = new javax.swing.JTextField();
        jComboBox_Datos_Equipo = new javax.swing.JComboBox<>();
        jButton_Añadir_Campeonato = new javax.swing.JButton();
        jTextField_Tipo_Campeonato = new javax.swing.JTextField();
        jTextField_Numero_Victorias = new javax.swing.JTextField();
        jTextField_Fechas_Victorias = new javax.swing.JTextField();
        jComboBox_Equipo_Campeon = new javax.swing.JComboBox<>();
        jLabelIUPDATES = new javax.swing.JLabel();
        jComboBoxEquipos = new javax.swing.JComboBox<>();
        jLabel_Nombre = new javax.swing.JLabel();
        jLabel_Ciudad = new javax.swing.JLabel();
        jLabel_Estadio = new javax.swing.JLabel();
        jLabel_Division = new javax.swing.JLabel();
        jTextField_Modf_Nombre_Equipo = new javax.swing.JTextField();
        jTextField_Modf_Ciudad = new javax.swing.JTextField();
        jTextField_Modf_Estadio = new javax.swing.JTextField();
        jTextField_Modf_Division = new javax.swing.JTextField();
        jButtonModificar = new javax.swing.JButton();
        jLabelDELETES = new javax.swing.JLabel();
        jButton_Borrar_Equipo = new javax.swing.JButton();
        jTextField_Nombre_borrar_Equip = new javax.swing.JTextField();
        jButton_Borrar_Datos = new javax.swing.JButton();
        jComboBox_Datos_Borrar = new javax.swing.JComboBox<>();
        jButton_Borrar_Campeonato = new javax.swing.JButton();
        jTextField_Campeonato_Borrar = new javax.swing.JTextField();
        jComboBox_Equipo_Campeon_Borrar = new javax.swing.JComboBox<>();
        jLabelSELECTS = new javax.swing.JLabel();
        jButtonBuscar_Equipo = new javax.swing.JButton();
        jTextFieldBuscar_Equipo = new javax.swing.JTextField();
        jButtonSelectAll = new javax.swing.JButton();
        jButtonSelect_Equipos = new javax.swing.JButton();
        jButtonSelect_Datos = new javax.swing.JButton();
        jButtonSelect_Campeonatos = new javax.swing.JButton();

        jDialog1.setResizable(false);
        jDialog1.setSize(new java.awt.Dimension(500, 650));

        jTextAreaQuerys.setEditable(false);
        jTextAreaQuerys.setBackground(new java.awt.Color(0, 255, 51));
        jTextAreaQuerys.setColumns(20);
        jTextAreaQuerys.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTextAreaQuerys.setRows(5);
        jScrollPane1.setViewportView(jTextAreaQuerys);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelManejo.setBackground(new java.awt.Color(0, 204, 51));
        jLabelManejo.setText("MANEJAR CONEXIÓN CON LA BBDD");
        jLabelManejo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelManejo.setOpaque(true);

        jButtonConectar.setBackground(new java.awt.Color(0, 255, 153));
        jButtonConectar.setText("Conectar/Actualizar");
        jButtonConectar.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConectarActionPerformed(evt);
            }
        });

        jButtonDesconectar.setBackground(new java.awt.Color(0, 255, 153));
        jButtonDesconectar.setText("Desconectar");
        jButtonDesconectar.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDesconectarActionPerformed(evt);
            }
        });

        jButtonModoDia.setBackground(new java.awt.Color(0, 255, 153));
        jButtonModoDia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-salida-del-sol-32.png"))); // NOI18N
        jButtonModoDia.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonModoDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModoDiaActionPerformed(evt);
            }
        });

        jButtonModoNoche.setBackground(new java.awt.Color(0, 255, 153));
        jButtonModoNoche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-luna-brillante-32 (2).png"))); // NOI18N
        jButtonModoNoche.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonModoNoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModoNocheActionPerformed(evt);
            }
        });

        jLabelINSERTS.setBackground(new java.awt.Color(0, 204, 51));
        jLabelINSERTS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelINSERTS.setText("INSERTAR  DATOS");
        jLabelINSERTS.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelINSERTS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelINSERTS.setOpaque(true);

        jButton_Añadir_Equipo.setBackground(new java.awt.Color(0, 255, 153));
        jButton_Añadir_Equipo.setText("AÑADIR EQUIPO");
        jButton_Añadir_Equipo.setBorder(new javax.swing.border.MatteBorder(null));
        jButton_Añadir_Equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Añadir_EquipoActionPerformed(evt);
            }
        });

        jTextField_Nombre_Equipo.setBackground(new java.awt.Color(0, 255, 51));
        jTextField_Nombre_Equipo.setToolTipText("Nombre");

        jTextField_Ciudad_Equipo.setBackground(new java.awt.Color(0, 255, 51));
        jTextField_Ciudad_Equipo.setToolTipText("Ciudad");

        jTextField_Estadio_Equipo.setBackground(new java.awt.Color(0, 255, 51));
        jTextField_Estadio_Equipo.setToolTipText("Estadio");

        jButton_Añadir_Datos.setBackground(new java.awt.Color(0, 255, 153));
        jButton_Añadir_Datos.setText("AÑADIR DATOS");
        jButton_Añadir_Datos.setBorder(new javax.swing.border.MatteBorder(null));
        jButton_Añadir_Datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Añadir_DatosActionPerformed(evt);
            }
        });

        jTextField_Conferencia.setBackground(new java.awt.Color(0, 255, 51));
        jTextField_Conferencia.setToolTipText("Conferencia");

        jTextField_Division.setBackground(new java.awt.Color(0, 255, 51));
        jTextField_Division.setToolTipText("División");

        jTextField_Fundacion.setBackground(new java.awt.Color(0, 255, 51));
        jTextField_Fundacion.setToolTipText("Fundación");

        jTextField_Entrada_NFL.setBackground(new java.awt.Color(0, 255, 51));
        jTextField_Entrada_NFL.setToolTipText("Entrada en la NFL");

        jComboBox_Datos_Equipo.setBackground(new java.awt.Color(0, 255, 153));
        jComboBox_Datos_Equipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton_Añadir_Campeonato.setBackground(new java.awt.Color(0, 255, 153));
        jButton_Añadir_Campeonato.setText("AÑADIR CAMPEONATO");
        jButton_Añadir_Campeonato.setBorder(new javax.swing.border.MatteBorder(null));
        jButton_Añadir_Campeonato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Añadir_CampeonatoActionPerformed(evt);
            }
        });

        jTextField_Tipo_Campeonato.setBackground(new java.awt.Color(0, 255, 51));
        jTextField_Tipo_Campeonato.setToolTipText("Campeonato");

        jTextField_Numero_Victorias.setBackground(new java.awt.Color(0, 255, 51));
        jTextField_Numero_Victorias.setToolTipText("Victorias");

        jTextField_Fechas_Victorias.setBackground(new java.awt.Color(0, 255, 51));
        jTextField_Fechas_Victorias.setToolTipText("Fechas");

        jComboBox_Equipo_Campeon.setBackground(new java.awt.Color(0, 255, 153));
        jComboBox_Equipo_Campeon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelIUPDATES.setBackground(new java.awt.Color(0, 204, 51));
        jLabelIUPDATES.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIUPDATES.setText("MODIFICAR  DATOS");
        jLabelIUPDATES.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelIUPDATES.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelIUPDATES.setOpaque(true);

        jComboBoxEquipos.setBackground(new java.awt.Color(0, 255, 153));
        jComboBoxEquipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel_Nombre.setBackground(new java.awt.Color(0, 204, 51));
        jLabel_Nombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_Nombre.setText("NOMBRE:");
        jLabel_Nombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_Nombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel_Nombre.setOpaque(true);

        jLabel_Ciudad.setBackground(new java.awt.Color(0, 204, 51));
        jLabel_Ciudad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_Ciudad.setText("CIUDAD:");
        jLabel_Ciudad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_Ciudad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel_Ciudad.setOpaque(true);

        jLabel_Estadio.setBackground(new java.awt.Color(0, 204, 51));
        jLabel_Estadio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_Estadio.setText("ESTADIO:");
        jLabel_Estadio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_Estadio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel_Estadio.setOpaque(true);

        jLabel_Division.setBackground(new java.awt.Color(0, 204, 51));
        jLabel_Division.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_Division.setText("DIVISIÓN:");
        jLabel_Division.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_Division.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel_Division.setOpaque(true);

        jTextField_Modf_Nombre_Equipo.setBackground(new java.awt.Color(0, 255, 51));
        jTextField_Modf_Nombre_Equipo.setToolTipText("");

        jTextField_Modf_Ciudad.setBackground(new java.awt.Color(0, 255, 51));
        jTextField_Modf_Ciudad.setToolTipText("");

        jTextField_Modf_Estadio.setBackground(new java.awt.Color(0, 255, 51));
        jTextField_Modf_Estadio.setToolTipText("");

        jTextField_Modf_Division.setBackground(new java.awt.Color(0, 255, 51));
        jTextField_Modf_Division.setToolTipText("");

        jButtonModificar.setBackground(new java.awt.Color(0, 255, 153));
        jButtonModificar.setText("MODIFICAR");
        jButtonModificar.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificar_EquipoActionPerformed(evt);
            }
        });

        jLabelDELETES.setBackground(new java.awt.Color(0, 204, 51));
        jLabelDELETES.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDELETES.setText("BORRAR  DATOS");
        jLabelDELETES.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelDELETES.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelDELETES.setOpaque(true);

        jButton_Borrar_Equipo.setBackground(new java.awt.Color(0, 255, 153));
        jButton_Borrar_Equipo.setText("BORAR EQUIPO");
        jButton_Borrar_Equipo.setBorder(new javax.swing.border.MatteBorder(null));
        jButton_Borrar_Equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Borrar_EquipoActionPerformed(evt);
            }
        });

        jTextField_Nombre_borrar_Equip.setBackground(new java.awt.Color(0, 255, 51));
        jTextField_Nombre_borrar_Equip.setToolTipText("Nombre del equipo");

        jButton_Borrar_Datos.setBackground(new java.awt.Color(0, 255, 153));
        jButton_Borrar_Datos.setText("BORRAR DATOS");
        jButton_Borrar_Datos.setBorder(new javax.swing.border.MatteBorder(null));
        jButton_Borrar_Datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Borrar_DatosActionPerformed(evt);
            }
        });

        jComboBox_Datos_Borrar.setBackground(new java.awt.Color(0, 255, 153));
        jComboBox_Datos_Borrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton_Borrar_Campeonato.setBackground(new java.awt.Color(0, 255, 153));
        jButton_Borrar_Campeonato.setText("BORRAR CAMPEONATO");
        jButton_Borrar_Campeonato.setBorder(new javax.swing.border.MatteBorder(null));
        jButton_Borrar_Campeonato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Borrar_CampeonatoActionPerformed(evt);
            }
        });

        jTextField_Campeonato_Borrar.setBackground(new java.awt.Color(0, 255, 51));
        jTextField_Campeonato_Borrar.setToolTipText("Campeonato");

        jComboBox_Equipo_Campeon_Borrar.setBackground(new java.awt.Color(0, 255, 153));
        jComboBox_Equipo_Campeon_Borrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelSELECTS.setBackground(new java.awt.Color(0, 204, 51));
        jLabelSELECTS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSELECTS.setText("CONSULTAR  DATOS");
        jLabelSELECTS.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelSELECTS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelSELECTS.setOpaque(true);

        jButtonBuscar_Equipo.setBackground(new java.awt.Color(0, 255, 153));
        jButtonBuscar_Equipo.setText("BUSCAR EQUIPO");
        jButtonBuscar_Equipo.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonBuscar_Equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscar_EquipoActionPerformed(evt);
            }
        });

        jTextFieldBuscar_Equipo.setBackground(new java.awt.Color(0, 255, 51));
        jTextFieldBuscar_Equipo.setToolTipText("Nombre de la Cancion");

        jButtonSelectAll.setBackground(new java.awt.Color(0, 255, 153));
        jButtonSelectAll.setText("CONSULTAR TODO");
        jButtonSelectAll.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonSelectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectAllActionPerformed(evt);
            }
        });

        jButtonSelect_Equipos.setBackground(new java.awt.Color(0, 255, 153));
        jButtonSelect_Equipos.setText("CONSULTAR EQUIPOS");
        jButtonSelect_Equipos.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonSelect_Equipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelect_EquiposActionPerformed(evt);
            }
        });

        jButtonSelect_Datos.setBackground(new java.awt.Color(0, 255, 153));
        jButtonSelect_Datos.setText("CONSULTAR DATOS");
        jButtonSelect_Datos.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonSelect_Datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelect_DatosActionPerformed(evt);
            }
        });

        jButtonSelect_Campeonatos.setBackground(new java.awt.Color(0, 255, 153));
        jButtonSelect_Campeonatos.setText("CONSULTAR CAMPEONATOS");
        jButtonSelect_Campeonatos.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonSelect_Campeonatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelect_CampeonatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelINSERTS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField_Nombre_Equipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                .addComponent(jTextField_Ciudad_Equipo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_Estadio_Equipo, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jButton_Añadir_Equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Conferencia)
                            .addComponent(jTextField_Division)
                            .addComponent(jTextField_Fundacion)
                            .addComponent(jButton_Añadir_Datos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_Entrada_NFL, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox_Datos_Equipo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField_Tipo_Campeonato)
                            .addComponent(jTextField_Numero_Victorias)
                            .addComponent(jButton_Añadir_Campeonato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox_Equipo_Campeon, javax.swing.GroupLayout.Alignment.LEADING, 0, 215, Short.MAX_VALUE)
                            .addComponent(jTextField_Fechas_Victorias, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addComponent(jLabelDELETES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelIUPDATES, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSELECTS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonBuscar_Equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldBuscar_Equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonSelect_Equipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSelectAll, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSelect_Datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSelect_Campeonatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelManejo, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDesconectar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(jButtonModoDia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModoNoche, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel_Division, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxEquipos, 0, 173, Short.MAX_VALUE)
                            .addComponent(jLabel_Ciudad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Estadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_Modf_Division, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(jTextField_Modf_Ciudad)
                            .addComponent(jTextField_Modf_Estadio)
                            .addComponent(jTextField_Modf_Nombre_Equipo, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_Nombre_borrar_Equip, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Borrar_Equipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_Datos_Borrar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Borrar_Datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_Campeonato_Borrar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_Borrar_Campeonato, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(jComboBox_Equipo_Campeon_Borrar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonModoDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonModoNoche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelManejo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonDesconectar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabelINSERTS, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_Añadir_Equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Añadir_Datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Añadir_Campeonato, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Conferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Nombre_Equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Tipo_Campeonato, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Division, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Numero_Victorias, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Ciudad_Equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Fundacion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Estadio_Equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Entrada_NFL, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_Equipo_Campeon, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextField_Fechas_Victorias, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_Datos_Equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelIUPDATES, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Modf_Nombre_Equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Modf_Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Modf_Estadio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Estadio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Modf_Division, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Division, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelDELETES, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton_Borrar_Equipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Borrar_Datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Borrar_Campeonato, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_Campeonato_Borrar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_Nombre_borrar_Equip, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox_Datos_Borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_Equipo_Campeon_Borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelSELECTS, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonSelect_Datos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSelect_Campeonatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldBuscar_Equipo)
                            .addComponent(jButtonSelectAll, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSelect_Equipos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonBuscar_Equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTextField_Nombre_Equipo.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSelect_CampeonatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelect_CampeonatosActionPerformed
        jTextAreaQuerys.setText(ges.selectCampeonatos());
        jDialog1.setVisible(true);
    }//GEN-LAST:event_jButtonSelect_CampeonatosActionPerformed

    private void jButtonSelect_DatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelect_DatosActionPerformed
        jTextAreaQuerys.setText(ges.selectDatos());
        jDialog1.setVisible(true);
    }//GEN-LAST:event_jButtonSelect_DatosActionPerformed

    private void jButtonSelect_EquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelect_EquiposActionPerformed
        jTextAreaQuerys.setText(ges.selectEquipos());
        jDialog1.setVisible(true);
    }//GEN-LAST:event_jButtonSelect_EquiposActionPerformed

    private void jButtonSelectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectAllActionPerformed
        jTextAreaQuerys.setText(ges.selectAll());
        jDialog1.setVisible(true);
    }//GEN-LAST:event_jButtonSelectAllActionPerformed

    //los botones de las consultas muestran los datos en un textArea alojado en un jDialog para optimizar espacio en la interfaz
    private void jButtonBuscar_EquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscar_EquipoActionPerformed
        jTextAreaQuerys.setText(ges.buscarEquipo(jTextFieldBuscar_Equipo.getText()));
        jDialog1.setVisible(true);
        jTextFieldBuscar_Equipo.setText("");
    }//GEN-LAST:event_jButtonBuscar_EquipoActionPerformed

    private void jButton_Borrar_CampeonatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Borrar_CampeonatoActionPerformed
        String equipo = (String) jComboBox_Datos_Borrar.getSelectedItem();
        int equipo_campeon = Integer.parseInt(equipo.split(" ")[0]);
        ges.borrarCampeonato(jTextField_Campeonato_Borrar.getText(), equipo_campeon);
        jTextField_Campeonato_Borrar.setText("");
    }//GEN-LAST:event_jButton_Borrar_CampeonatoActionPerformed

    private void jButton_Borrar_DatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Borrar_DatosActionPerformed
        String equipo = (String) jComboBox_Datos_Borrar.getSelectedItem();
        int dato_equipo = Integer.parseInt(equipo.split(" ")[0]);
        ges.borrarDato(dato_equipo);
    }//GEN-LAST:event_jButton_Borrar_DatosActionPerformed

    private void jButton_Borrar_EquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Borrar_EquipoActionPerformed
        ges.borrarEquipo(jTextField_Nombre_borrar_Equip.getText());
        jTextField_Nombre_borrar_Equip.setText("");
    }//GEN-LAST:event_jButton_Borrar_EquipoActionPerformed

    private void jButtonModificar_EquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificar_EquipoActionPerformed
        String equipo = (String) jComboBoxEquipos.getSelectedItem();
        int id_equipo = Integer.parseInt(equipo.split(" ")[0]);
        ges.modificar(jTextField_Modf_Nombre_Equipo.getText(), jTextField_Modf_Ciudad.getText(), jTextField_Modf_Estadio.getText(), jTextField_Modf_Division.getText(), id_equipo);
        jTextField_Modf_Nombre_Equipo.setText("");
        jTextField_Modf_Ciudad.setText("");
        jTextField_Modf_Estadio.setText("");
        jTextField_Modf_Division.setText("");
    }//GEN-LAST:event_jButtonModificar_EquipoActionPerformed

    private void jButton_Añadir_CampeonatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Añadir_CampeonatoActionPerformed
        String equipo = (String) jComboBox_Datos_Equipo.getSelectedItem();
        int id_equipo = Integer.parseInt(equipo.split(" ")[0]);
        ges.insertarCampeonato(jTextField_Tipo_Campeonato.getText(), jTextField_Numero_Victorias.getText(), jTextField_Fechas_Victorias.getText(), id_equipo);
        jTextField_Tipo_Campeonato.setText("");
        jTextField_Numero_Victorias.setText("");
        jTextField_Fechas_Victorias.setText("");
    }//GEN-LAST:event_jButton_Añadir_CampeonatoActionPerformed

    private void jButton_Añadir_DatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Añadir_DatosActionPerformed
        String equipo = (String) jComboBox_Datos_Equipo.getSelectedItem();//creo una variable string y casteo el valor del combobox seleccionado*
        int id_equipo = Integer.parseInt(equipo.split(" ")[0]);//vuelvo a castear ese valor a int y le paso el valor 0(teniendo en cuenta que el id siempre esta en esa posicion)
        //del array creado por el split dividiendo el string por los espacios
        //esto evita errores de seleccion si se borrasen datos en la tabla*
ges.insertarDatos(jTextField_Conferencia.getText(), jTextField_Division.getText(), jTextField_Fundacion.getText(), jTextField_Entrada_NFL.getText(), id_equipo);
        jTextField_Conferencia.setText("");
        jTextField_Division.setText("");
        jTextField_Fundacion.setText("");
        jTextField_Entrada_NFL.setText("");
    }//GEN-LAST:event_jButton_Añadir_DatosActionPerformed

    private void jButton_Añadir_EquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Añadir_EquipoActionPerformed
        ges.insertarEquipo(jTextField_Nombre_Equipo.getText(), jTextField_Ciudad_Equipo.getText(), jTextField_Estadio_Equipo.getText());
        jTextField_Nombre_Equipo.setText("");
        jTextField_Ciudad_Equipo.setText("");
        jTextField_Estadio_Equipo.setText("");
    }//GEN-LAST:event_jButton_Añadir_EquipoActionPerformed

    private void jButtonModoNocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModoNocheActionPerformed
        modoNocheVerde();
    }//GEN-LAST:event_jButtonModoNocheActionPerformed

    private void jButtonModoDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModoDiaActionPerformed
        modoDiaVerde();
    }//GEN-LAST:event_jButtonModoDiaActionPerformed

    private void jButtonDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDesconectarActionPerformed
        ges.cerrar_conexion();
        deshabilitarBotones();
        Inicio ini = new Inicio();
        ini.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonDesconectarActionPerformed

    //este botón sirve a su vez para conectar con el servidor/bbdd como para actualizar la conexión en caso de cambios
    private void jButtonConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConectarActionPerformed

        if (ges.GestorConexion() == 0) {
            System.out.println("Conexión establecida correctamente");
            deshabilitarBotones();//esto es solo en el caso de haber conectado con la bbdd, borrarla y actualizar la conexión
            //con el combobox vacio lo rellena y luego habilita todos los botones
            rellenarBoxEquipos();
            conectar();
        } else if (ges.GestorConexion() == 1) {
            System.out.println("No fue posible establecer una conexión");
        } else {
            System.out.println("Error en la conexion");
        }
    }//GEN-LAST:event_jButtonConectarActionPerformed

    //este método rellena los combobox relacionados a los artistas con el método arraylist creado en la clase del gestor
    private void rellenarBoxEquipos() {
        //primero eimina los datos por defecto para llenarlos con los datos deseados
        jComboBox_Datos_Equipo.removeAllItems();
        jComboBox_Equipo_Campeon.removeAllItems();
        jComboBoxEquipos.removeAllItems();
        jComboBox_Datos_Borrar.removeAllItems();
        jComboBox_Equipo_Campeon_Borrar.removeAllItems();
        ArrayList<String> listaEquipos = new ArrayList<String>();//para la foreign key de album en canciones
        listaEquipos = ges.comboBoxEquipos();
        for (int i = 0; i < listaEquipos.size(); i++) {
            jComboBox_Datos_Equipo.addItem(listaEquipos.get(i));
            jComboBox_Equipo_Campeon.addItem(listaEquipos.get(i));
            jComboBoxEquipos.addItem(listaEquipos.get(i));
            jComboBox_Datos_Borrar.addItem(listaEquipos.get(i));
            jComboBox_Equipo_Campeon_Borrar.addItem(listaEquipos.get(i));
        }
    }

    //este método deshabilita todos los botones y vacia los combobox en caso de no estar conectado a la bbdd o de haber
    //finalizado la conexión
    private void deshabilitarBotones() {
        jButtonDesconectar.setEnabled(false);
        jButton_Añadir_Equipo.setEnabled(false);
        jButton_Añadir_Datos.setEnabled(false);
        jButton_Añadir_Campeonato.setEnabled(false);
        jButtonModificar.setEnabled(false);
        jButton_Borrar_Equipo.setEnabled(false);
        jButton_Borrar_Datos.setEnabled(false);
        jButton_Borrar_Campeonato.setEnabled(false);
        jButtonBuscar_Equipo.setEnabled(false);
        jButtonSelectAll.setEnabled(false);
        jButtonSelect_Datos.setEnabled(false);
        jButtonSelect_Equipos.setEnabled(false);
        jButtonSelect_Campeonatos.setEnabled(false);

        jComboBox_Datos_Equipo.removeAllItems();
        jComboBox_Equipo_Campeon.removeAllItems();
        jComboBoxEquipos.removeAllItems();
        jComboBox_Datos_Borrar.removeAllItems();
        jComboBox_Equipo_Campeon_Borrar.removeAllItems();

    }

    //este método habilita todos los botones de la interfaz, usado despues de haber conectado con la base de datos
    private void conectar() {
        jButton_Añadir_Equipo.setEnabled(true);
        jButton_Añadir_Datos.setEnabled(true);
        jButton_Añadir_Campeonato.setEnabled(true);
        jButtonModificar.setEnabled(true);
        jButton_Borrar_Equipo.setEnabled(true);
        jButton_Borrar_Datos.setEnabled(true);
        jButton_Borrar_Campeonato.setEnabled(true);
        jButtonBuscar_Equipo.setEnabled(true);
        jButtonSelectAll.setEnabled(true);
        jButtonSelect_Datos.setEnabled(true);
        jButtonSelect_Equipos.setEnabled(true);
        jButtonSelect_Campeonatos.setEnabled(true);
        jButtonDesconectar.setEnabled(true);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(false);
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar_Equipo;
    private javax.swing.JButton jButtonConectar;
    private javax.swing.JButton jButtonDesconectar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonModoDia;
    private javax.swing.JButton jButtonModoNoche;
    private javax.swing.JButton jButtonSelectAll;
    private javax.swing.JButton jButtonSelect_Campeonatos;
    private javax.swing.JButton jButtonSelect_Datos;
    private javax.swing.JButton jButtonSelect_Equipos;
    private javax.swing.JButton jButton_Añadir_Campeonato;
    private javax.swing.JButton jButton_Añadir_Datos;
    private javax.swing.JButton jButton_Añadir_Equipo;
    private javax.swing.JButton jButton_Borrar_Campeonato;
    private javax.swing.JButton jButton_Borrar_Datos;
    private javax.swing.JButton jButton_Borrar_Equipo;
    private javax.swing.JComboBox<String> jComboBoxEquipos;
    private javax.swing.JComboBox<String> jComboBox_Datos_Borrar;
    private javax.swing.JComboBox<String> jComboBox_Datos_Equipo;
    private javax.swing.JComboBox<String> jComboBox_Equipo_Campeon;
    private javax.swing.JComboBox<String> jComboBox_Equipo_Campeon_Borrar;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabelDELETES;
    private javax.swing.JLabel jLabelINSERTS;
    private javax.swing.JLabel jLabelIUPDATES;
    private javax.swing.JLabel jLabelManejo;
    private javax.swing.JLabel jLabelSELECTS;
    private javax.swing.JLabel jLabel_Ciudad;
    private javax.swing.JLabel jLabel_Division;
    private javax.swing.JLabel jLabel_Estadio;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaQuerys;
    private javax.swing.JTextField jTextFieldBuscar_Equipo;
    private javax.swing.JTextField jTextField_Campeonato_Borrar;
    private javax.swing.JTextField jTextField_Ciudad_Equipo;
    private javax.swing.JTextField jTextField_Conferencia;
    private javax.swing.JTextField jTextField_Division;
    private javax.swing.JTextField jTextField_Entrada_NFL;
    private javax.swing.JTextField jTextField_Estadio_Equipo;
    private javax.swing.JTextField jTextField_Fechas_Victorias;
    private javax.swing.JTextField jTextField_Fundacion;
    private javax.swing.JTextField jTextField_Modf_Ciudad;
    private javax.swing.JTextField jTextField_Modf_Division;
    private javax.swing.JTextField jTextField_Modf_Estadio;
    private javax.swing.JTextField jTextField_Modf_Nombre_Equipo;
    private javax.swing.JTextField jTextField_Nombre_Equipo;
    private javax.swing.JTextField jTextField_Nombre_borrar_Equip;
    private javax.swing.JTextField jTextField_Numero_Victorias;
    private javax.swing.JTextField jTextField_Tipo_Campeonato;
    // End of variables declaration//GEN-END:variables

    //estos dos métodos cambian el color del fondo y del texto de todos los componentes 
    //para ajustar la interfaz a un modo dia y uno noche
    public void modoNocheVerde() {
        jPanel1.setBackground(new java.awt.Color(0, 51, 0));
        jTextAreaQuerys.setBackground(new java.awt.Color(0, 153, 102));

        jLabelIUPDATES.setBackground(new java.awt.Color(0, 204, 51));
        jLabelSELECTS.setBackground(new java.awt.Color(0, 204, 51));
        jLabelDELETES.setBackground(new java.awt.Color(0, 204, 51));
        jLabelManejo.setBackground(new java.awt.Color(0, 204, 51));
        jLabelINSERTS.setBackground(new java.awt.Color(0, 204, 51));

        jTextField_Campeonato_Borrar.setBackground(new java.awt.Color(0, 153, 102));
        jTextField_Nombre_borrar_Equip.setBackground(new java.awt.Color(0, 153, 102));
        jTextField_Fundacion.setBackground(new java.awt.Color(0, 153, 102));
        jTextField_Modf_Nombre_Equipo.setBackground(new java.awt.Color(0, 153, 102));
        jTextField_Tipo_Campeonato.setBackground(new java.awt.Color(0, 153, 102));
        jTextField_Modf_Ciudad.setBackground(new java.awt.Color(0, 153, 102));
        jTextField_Numero_Victorias.setBackground(new java.awt.Color(0, 153, 102));
        jTextField_Nombre_Equipo.setBackground(new java.awt.Color(0, 153, 102));
        jTextField_Conferencia.setBackground(new java.awt.Color(0, 153, 102));
        jTextField_Division.setBackground(new java.awt.Color(0, 153, 102));
        jTextFieldBuscar_Equipo.setBackground(new java.awt.Color(0, 153, 102));
        jTextField_Ciudad_Equipo.setBackground(new java.awt.Color(0, 153, 102));
        jTextField_Estadio_Equipo.setBackground(new java.awt.Color(0, 153, 102));
        jTextField_Entrada_NFL.setBackground(new java.awt.Color(0, 153, 102));
        jTextField_Fechas_Victorias.setBackground(new java.awt.Color(0, 153, 102));
        jTextField_Modf_Estadio.setBackground(new java.awt.Color(0, 153, 102));
        jTextField_Modf_Division.setBackground(new java.awt.Color(0, 153, 102));

        jButton_Borrar_Campeonato.setBackground(new java.awt.Color(51, 102, 0));
        jButtonSelect_Equipos.setBackground(new java.awt.Color(51, 102, 0));
        jButtonSelectAll.setBackground(new java.awt.Color(51, 102, 0));
        jButtonSelect_Campeonatos.setBackground(new java.awt.Color(51, 102, 0));
        jButtonSelect_Datos.setBackground(new java.awt.Color(51, 102, 0));
        jButtonConectar.setBackground(new java.awt.Color(51, 102, 0));
        jButton_Añadir_Equipo.setBackground(new java.awt.Color(51, 102, 0));
        jButton_Añadir_Datos.setBackground(new java.awt.Color(51, 102, 0));
        jButtonModificar.setBackground(new java.awt.Color(51, 102, 0));
        jButton_Añadir_Campeonato.setBackground(new java.awt.Color(51, 102, 0));
        jButtonDesconectar.setBackground(new java.awt.Color(51, 102, 0));
        jButton_Borrar_Equipo.setBackground(new java.awt.Color(51, 102, 0));
        jButtonBuscar_Equipo.setBackground(new java.awt.Color(51, 102, 0));
        jButton_Borrar_Datos.setBackground(new java.awt.Color(51, 102, 0));
        jButtonModoNoche.setBackground(new java.awt.Color(51, 102, 0));
        jButtonModoDia.setBackground(new java.awt.Color(51, 102, 0));

        jComboBoxEquipos.setBackground(new java.awt.Color(51, 102, 0));
        jComboBox_Datos_Equipo.setBackground(new java.awt.Color(51, 102, 0));
        jComboBox_Equipo_Campeon.setBackground(new java.awt.Color(51, 102, 0));
        jComboBox_Datos_Borrar.setBackground(new java.awt.Color(51, 102, 0));
        jComboBox_Equipo_Campeon_Borrar.setBackground(new java.awt.Color(51, 102, 0));

        jTextAreaQuerys.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Borrar_Campeonato.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSelect_Equipos.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Nombre_borrar_Equip.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSelectAll.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Campeonato_Borrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSelect_Campeonatos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSelect_Datos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIUPDATES.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConectar.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxEquipos.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Fundacion.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Modf_Nombre_Equipo.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Tipo_Campeonato.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Modf_Ciudad.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Numero_Victorias.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Ciudad_Equipo.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Estadio_Equipo.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Entrada_NFL.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Fechas_Victorias.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Modf_Estadio.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Modf_Division.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Añadir_Equipo.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Añadir_Datos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModificar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Añadir_Campeonato.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox_Datos_Equipo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSELECTS.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox_Equipo_Campeon.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDELETES.setForeground(new java.awt.Color(255, 255, 255));
        jLabelManejo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDesconectar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelINSERTS.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Nombre_Equipo.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Conferencia.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Division.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldBuscar_Equipo.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Borrar_Equipo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBuscar_Equipo.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Borrar_Datos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModoNoche.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModoDia.setForeground(new java.awt.Color(255, 255, 255));
    }

    public void modoDiaVerde() {
        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jTextAreaQuerys.setBackground(new java.awt.Color(0, 255, 51));

        jLabelIUPDATES.setBackground(new java.awt.Color(0, 204, 51));
        jLabelSELECTS.setBackground(new java.awt.Color(0, 204, 51));
        jLabelDELETES.setBackground(new java.awt.Color(0, 204, 51));
        jLabelManejo.setBackground(new java.awt.Color(0, 204, 51));
        jLabelINSERTS.setBackground(new java.awt.Color(0, 204, 51));

        jTextField_Nombre_borrar_Equip.setBackground(new java.awt.Color(0, 255, 51));
        jTextField_Nombre_Equipo.setBackground(new java.awt.Color(0, 255, 51));
        jTextField_Conferencia.setBackground(new java.awt.Color(0, 255, 51));
        jTextField_Division.setBackground(new java.awt.Color(0, 255, 51));
        jTextFieldBuscar_Equipo.setBackground(new java.awt.Color(0, 255, 51));
        jTextField_Campeonato_Borrar.setBackground(new java.awt.Color(0, 255, 51));
        jTextField_Fundacion.setBackground(new java.awt.Color(0, 255, 51));
        jTextField_Modf_Nombre_Equipo.setBackground(new java.awt.Color(0, 255, 51));
        jTextField_Tipo_Campeonato.setBackground(new java.awt.Color(0, 255, 51));
        jTextField_Modf_Ciudad.setBackground(new java.awt.Color(0, 255, 51));
        jTextField_Numero_Victorias.setBackground(new java.awt.Color(0, 255, 51));
        jTextField_Ciudad_Equipo.setBackground(new java.awt.Color(0, 255, 51));
        jTextField_Estadio_Equipo.setBackground(new java.awt.Color(0, 255, 51));
        jTextField_Entrada_NFL.setBackground(new java.awt.Color(0, 255, 51));
        jTextField_Fechas_Victorias.setBackground(new java.awt.Color(0, 255, 51));
        jTextField_Modf_Estadio.setBackground(new java.awt.Color(0, 255, 51));
        jTextField_Modf_Division.setBackground(new java.awt.Color(0, 255, 51));

        jButton_Borrar_Campeonato.setBackground(new java.awt.Color(0, 255, 153));
        jButtonSelect_Equipos.setBackground(new java.awt.Color(0, 255, 153));
        jButtonSelectAll.setBackground(new java.awt.Color(0, 255, 153));
        jButtonSelect_Campeonatos.setBackground(new java.awt.Color(0, 255, 153));
        jButtonSelect_Datos.setBackground(new java.awt.Color(0, 255, 153));
        jButtonConectar.setBackground(new java.awt.Color(0, 255, 153));
        jButton_Añadir_Equipo.setBackground(new java.awt.Color(0, 255, 153));
        jButton_Añadir_Datos.setBackground(new java.awt.Color(0, 255, 153));
        jButtonModificar.setBackground(new java.awt.Color(0, 255, 153));
        jButton_Añadir_Campeonato.setBackground(new java.awt.Color(0, 255, 153));
        jButtonDesconectar.setBackground(new java.awt.Color(0, 255, 153));
        jButton_Borrar_Equipo.setBackground(new java.awt.Color(0, 255, 153));
        jButtonBuscar_Equipo.setBackground(new java.awt.Color(0, 255, 153));
        jButton_Borrar_Datos.setBackground(new java.awt.Color(0, 255, 153));
        jButtonModoNoche.setBackground(new java.awt.Color(0, 255, 153));
        jButtonModoDia.setBackground(new java.awt.Color(0, 255, 153));

        jComboBoxEquipos.setBackground(new java.awt.Color(0, 255, 153));
        jComboBox_Datos_Equipo.setBackground(new java.awt.Color(0, 255, 153));
        jComboBox_Equipo_Campeon.setBackground(new java.awt.Color(0, 255, 153));
        jComboBox_Datos_Borrar.setBackground(new java.awt.Color(0, 255, 153));
        jComboBox_Equipo_Campeon_Borrar.setBackground(new java.awt.Color(0, 255, 153));

        jTextAreaQuerys.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Borrar_Campeonato.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSelect_Equipos.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Nombre_borrar_Equip.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSelectAll.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Campeonato_Borrar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSelect_Campeonatos.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSelect_Datos.setForeground(new java.awt.Color(0, 0, 0));
        jLabelIUPDATES.setForeground(new java.awt.Color(0, 0, 0));
        jButtonConectar.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxEquipos.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Fundacion.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Modf_Nombre_Equipo.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Tipo_Campeonato.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Modf_Ciudad.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Numero_Victorias.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Ciudad_Equipo.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Estadio_Equipo.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Entrada_NFL.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Fechas_Victorias.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Modf_Estadio.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Modf_Division.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Añadir_Equipo.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Añadir_Datos.setForeground(new java.awt.Color(0, 0, 0));
        jButtonModificar.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Añadir_Campeonato.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox_Datos_Equipo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSELECTS.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox_Equipo_Campeon.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDELETES.setForeground(new java.awt.Color(0, 0, 0));
        jLabelManejo.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDesconectar.setForeground(new java.awt.Color(0, 0, 0));
        jLabelINSERTS.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Nombre_Equipo.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Conferencia.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Division.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldBuscar_Equipo.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Borrar_Equipo.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBuscar_Equipo.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Borrar_Datos.setForeground(new java.awt.Color(0, 0, 0));
        jButtonModoNoche.setForeground(new java.awt.Color(0, 0, 0));
        jButtonModoDia.setForeground(new java.awt.Color(0, 0, 0));
    }

}
